In [1]:
# import necessary modules
import smtplib
import pandas as pd
import os
import glob
import sys
import sched
import time
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

In [2]:
# set home directory so can be used on all OS
home = os.path.expanduser('~')

# Find most recently exported files from registry and repository
# (please note that one could also easily modify script to specify files you wish to use, but as we're trying to minimize RDRP data that's stored on machines, requiring download immediately before and then automating deletion within this script facilitates that end goal)
# reg_file should be report XX
# repo_file should be report XX
# link_file should be downloaded from XX as according to wiki
reg_file = max(glob.iglob(home+'/Downloads/RDRPRegistry-Emails_DATA_*'), key=os.path.getctime)
repo_file = max(glob.iglob(home+'/Downloads/RDRPRepository-SurveyStatus_DATA_*'), key=os.path.getctime)
link_file = max(glob.iglob(home+'/Downloads/RDRPRepository_Participants_*'), key=os.path.getctime)

In [ ]:
# Load data from each using record_id as index
reg_data = pd.read_csv(reg_file, index_col='record_id', dtype=object)
repo_data = pd.read_csv(repo_file, index_col='record_id')
link_data = pd.read_csv(link_file, skiprows=1, header=None, names=['dummy', 'na',
    'record_id', 'd', 'e', 'f', 'survey', 'link'], index_col='record_id', dtype=object) # headers in the file are poorly written. na, d, e, f are all not used

# Extract links for survey queues via innerjoin
reg_data = reg_data.join(link_data)

# Use the repo_data to select which individuals will receive emails
subs = pd.DataFrame(reg_data.loc[repo_data.index])

In [33]:
reg_data

,redcap_event_name,email,parent_first_name,parent_last_name,first_name,last_name,dummy,na,d,e,f,survey,link
record_id,,,,,,,,,,,,,
1,subject_intake_arm_1,tmgoodall@comcast.net,Tina,Goodall,Lily,Goodall,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,subject_intake_arm_1,Jmsonnenfeld@hotmail.com,Jacquie,Sonnenfeld,Reeghan,Sonnenfeld,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,subject_intake_arm_1,juliabacharach@msn.com,Julia,Bacharach,Ariana,Cory,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,subject_intake_arm_1,nicolebainphd@gmail.com,Nicole,Bain,Lincoln,Bain,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,subject_intake_arm_1,nicolebainphd@gmail.com,Nicole,Bain,Bishop,Bain,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2321,subject_intake_arm_1,dstall@gmail.com,Danny,Kelly-Stallings,Amos,Kelly-Stallings,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2324,subject_intake_arm_1,kari.ginal@gmail.com,Kari,Ginal,Maxwell,Ginal,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2326,subject_intake_arm_1,tysonz.sfw@gmail.com,Tyson,Zevenbergen,Trevor,Zevenbergen,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2330,subject_intake_arm_1,m_branson@hotmail.com,Margaret,Baker,Benjamin,Baker,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2334,subject_intake_arm_1,catherinekovell@gmail.com,Catherine,Kovell,Tal,Kovell,NaN,NaN,NaN,NaN,NaN,NaN,NaN